### 1.Write python code to create array in different ways


In [1]:
import numpy as py

In [3]:
arr = py.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [5]:
## method 2 using tuple:
arr = py.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [7]:
# method 3-  np.zeros()-array filled with all zeros

arr = py.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [8]:
# method 4- np.ones()-array filled with all ones

arr = py.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [9]:
# method 5- np.arange()-array filled with regularly spaced values

arr = py.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# method 6 - np.linspace()-array filled with evenly spaced values

arr = py.linspace(1,10,4)
arr

array([ 1.,  4.,  7., 10.])

## 2.array creation
a.create a 1D Numpy array containing the first 12 positive integer as arr1

In [13]:
arr1 = py.arange(1,13)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
len(arr1)

12

In [15]:
type(arr1)

numpy.ndarray

In [16]:
id(arr1)

2224498439056

## b.create a 1D Numpy array1 with 20 elements containing integer between 0 and 12 using linspace

In [17]:
arr2= py.linspace(1,12,20)

In [18]:
arr2

array([ 1.        ,  1.57894737,  2.15789474,  2.73684211,  3.31578947,
        3.89473684,  4.47368421,  5.05263158,  5.63157895,  6.21052632,
        6.78947368,  7.36842105,  7.94736842,  8.52631579,  9.10526316,
        9.68421053, 10.26315789, 10.84210526, 11.42105263, 12.        ])

In [19]:
len(arr2)

20

In [20]:
type(arr2)

numpy.ndarray

In [21]:
id(arr2)

2224498440112

## 3.find all attributes of arr1 and arr2


### arr1

In [22]:
arr1.dtype

dtype('int32')

In [23]:
arr1.size

12

In [24]:
arr1.nbytes

48

In [25]:
arr1.itemsize

4

### arr2

In [26]:
arr2.dtype

dtype('float64')

In [27]:
arr2.size

20

In [28]:
arr2.nbytes

160

In [29]:
arr2.itemsize

8

## 4.apply measure and describe the data(attribue and statistics) to above arrays using Numpy

### arr1

In [30]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
py.mean(arr1)

6.5

In [32]:
py.median(arr1)

6.5

In [33]:
range = max(arr1) - min(arr1)
range

11

In [34]:
py.var(arr1)

11.916666666666666

In [35]:
py.std(arr1)

3.452052529534663

In [36]:
q1 = py.percentile(arr1,25)
q3 = py.percentile(arr1,75)
IQR = q3- q1
IQR

5.5

In [38]:
lower_limit = q1 - (1.5)*(IQR)
print("lower_limit:",lower_limit)
upper_limit = q3 + (1.5)*(IQR)
print("upper_limit:",upper_limit)

lower_limit: -4.5
upper_limit: 17.5


In [39]:
print(arr1[arr1>upper_limit])  # outlier-there is no outliers in arr1
print(arr1[arr1<lower_limit])

[]
[]


### arr2

In [40]:
arr2

array([ 1.        ,  1.57894737,  2.15789474,  2.73684211,  3.31578947,
        3.89473684,  4.47368421,  5.05263158,  5.63157895,  6.21052632,
        6.78947368,  7.36842105,  7.94736842,  8.52631579,  9.10526316,
        9.68421053, 10.26315789, 10.84210526, 11.42105263, 12.        ])

In [41]:
py.mean(arr2)

6.5

In [42]:
py.median(arr2)

6.5

In [44]:
py.var(arr2)

11.144736842105264

In [45]:
py.std(arr2)

3.338373382667862

In [46]:
Range = max(arr2) - min(arr2) # Range-max-min
Range

11.0

In [48]:
q3 = py.percentile(arr2,75) 
q1 = py.percentile(arr2,25)  # Range = max-min
IQR =q3 - q1
IQR

5.5

In [49]:
lower_limit = q1 - (1.5)*(IQR)
print("lower_limit:",lower_limit)
upper_limit = q3 + (1.5)*(IQR)
print("upper_limit:",upper_limit)

lower_limit: -4.5
upper_limit: 17.5


In [50]:
print(arr1[arr1>upper_limit])  # outlier-there is no outliers in arr2
print(arr1[arr1<lower_limit])

[]
[]
